### ISSUE TITLE
Push not working on Windows

### ISSUE THREAD

**Issue by michael081906** [skylar09/Summer-Research#7]
Hi Skylar, 
I installed git on my Win10 this morning and was able to push a local change to the repo. 

When I installed the git, I noticed that I used the second option for my backend (See the image below). The default one is the first option using ssh. I don't know which one you choose, but it seems a lot of people are having the same issue. [See the Post](https://stackoverflow.com/questions/35077787/git-push-not-working-no-error)

![image](https://user-images.githubusercontent.com/31603609/128244577-2f6fd32f-08e0-49cc-826e-010026d66afc.png)

My suggestion will be to try how to change such configuration in your existing setup. If not, you can try to uninstall and then reinstall the git for choosing such option when installing.

**Comment by skylar09** [comment]
I reinstalled git and reconfigured it with that option I was able to push the document I wanted to save. But I realised it did not save what I wanted it to
